### ISSUE TITLE
Sequence "X" not present

### ISSUE THREAD

**Issue by RenscoHogers** [eldariont/svim-asm#25]
Dear developers,

I am trying to use SVIM-asm for structural variation analyses between two genomes.
Unfortunately I run into an error that looks as follows:
`
2023-08-17 15:51:43,499 [INFO   ]  ****************** STEP 2: OUTPUT ******************
2023-08-17 15:51:43,499 [INFO   ]  Found 10143 deletion candidates.
2023-08-17 15:51:43,499 [INFO   ]  Found 31 inversion candidates.
2023-08-17 15:51:43,500 [INFO   ]  Found 14641 insertion candidates.
2023-08-17 15:51:43,500 [INFO   ]  Found 31 tandem duplication candidates.
2023-08-17 15:51:43,500 [INFO   ]  Found 0 interspersed duplication candidates.
2023-08-17 15:51:43,500 [INFO   ]  Found 118 breakend candidates.
2023-08-17 15:51:43,500 [INFO   ]  Write SV candidates..
2023-08-17 15:51:43,502 [ERROR  ]  "sequence 'NC_037328.1' not present"
Traceback (most recent call last):
  File "/home/WUR/hoger006/lustre_dir/Tools/mambaforge/envs/svimasm/bin/svim-asm", line 183, in <module>
    sys.exit(main())
  File "/home/WUR/hoger006/lustre_dir/Tools/mambaforge/envs/svimasm/bin/svim-asm", line 165, in main
    write_final_vcf(interspersed_duplication_candidates,
  File "/home/WUR/hoger006/lustre_dir/Tools/mambaforge/envs/svimasm/lib/python3.10/site-packages/svim_asm/SVIM_COMBINE.py", line 434, in write_final_vcf
    vcf_entries.append(((contig, max(1, start), end), candidate.get_vcf_entry(sequence_alleles, reference, options.query_names), "DEL"))
  File "/home/WUR/hoger006/lustre_dir/Tools/mambaforge/envs/svimasm/lib/python3.10/site-packages/svim_asm/SVCandidate.py", line 57, in get_vcf_entry
    ref_allele = reference.fetch(contig, max(0, start-1), end).upper()
  File "pysam/libcfaidx.pyx", line 301, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'NC_037328.1' not present"
`

I am not entirely sure how the tools runs through the entire analysis, mapping, sorting, indexing, collecting and outputs the amount of present structural variations, and then fails when it is trying to save the results.
Do you have any suggestions for what might be going wrong? I have tried rerunning the scaffolding on the reference genome, rerunning SVIM-asm and using a different genome to compare to the reference, but none of these resolve the issue.

Thanks in advance!

**Comment by RenscoHogers** [comment]
It seems that I made a typo in one of the two reference file location, causing the software to not being able to find the correct file contig headers. My apologies.
